#!/bin/bash
#SBATCH -p gpu -n 9 --gres=gpu:6 -c1 --hint=nomultithread -t 2-00:00
#  (Note: use one MPI process per gpu, update both gres and -n together; max 6)
export PYTHONPATH=/home/mchandra/gitansh/merge_to_master; time mpirun python main.py > output.txt
