#!/bin/bash
#SBATCH -p gpu -n 1 --gres=gpu:1 -c1 --hint=nomultithread -t 2-00:00
#  (Note: use one MPI process per gpu, update both gres and -n together; max 6)
export PYTHONPATH=/home/mchandra/gitansh/arbitrary_reflection; time mpirun python main.py > output.txt
